version: "3"

networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik
    networks:
      - proxy
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    command: -c /dev/null --api --docker --docker.domain=vsecko.doma --logLevel=DEBUG
    labels:
      traefik.frontend.rule: "Host:traefik.vsecko.doma"
      traefik.port: 8080
