version: "3"

networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik
    networks:
      - proxy
    ports:
      - 80:80
      - 8080:8080
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    command: -c /dev/null --api --docker --docker.domain=vsecko.doma --logLevel=DEBUG
    labels:
      traefik.frontend.rule: "Host:traefik.${DOMAIN}"
      traefik.port: 8080
      traefik.docker.network: proxy
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      TZ: ${TZ}
    env_file:
      - .env
    networks:
      - proxy
    volumes:
      - ${DATA_DIR}/config/heimdall:/config
    # ports:
    #   - 80:80
    labels:
      traefik.frontend.rule: "Host:${DOMAIN}"
      traefik.port: 80
      traefik.docker.network: proxy
