version: "3"

networks:
  proxy:
    external: true

services:
  db:
    image: postgres:alpine
    volumes:
      - ${DATA_DIR}/config/nextcloud/postgres:/var/lib/postgresql/data
    env_file:
      - .env
  nextcloud:
    image: nextcloud:fpm-alpine
    volumes:
      - ${DATA_DIR}/config/nextcloud:/var/www/html
      - ${DATA_DIR}/content:/var/www/html/data
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env
    depends_on:
      - db
  nextcloud_web:
    build: ./web
    volumes:
      - ${DATA_DIR}/config/nextcloud:/var/www/html:ro
      - ${DATA_DIR}/content:/var/www/html/data:ro
    environment:
      - VIRTUAL_HOST=cloud.${DOMAIN}
    depends_on:
      - nextcloud
    networks:
      - proxy
    labels:
      traefik.frontend.rule: "Host:cloud.${DOMAIN}"
      traefik.port: 80
