version: "3"

networks:
  proxy:
    external: true

services:
  db:
    image: postgres:alpine
    volumes:
      - ${DATA_DIR}/config/nextcloud/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - default
    labels:
      traefik.enable: false
  app:
    image: nextcloud:fpm-alpine
    volumes:
      - ${DATA_DIR}/config/nextcloud:/var/www/html
      - ${DATA_DIR}/content:/var/www/html/data
    environment:
      - POSTGRES_HOST=db
    links:
      - db
    networks:
      - default
    env_file:
      - .env
    depends_on:
      - db
    labels:
      traefik.enable: false
  proxy:
    build: ./web
    volumes:
      - ${DATA_DIR}/config/nextcloud:/var/www/html:ro
      - ${DATA_DIR}/content:/var/www/html/data:ro
    environment:
      - VIRTUAL_HOST=cloud.${DOMAIN}
    links:
      - app
    depends_on:
      - app
    env_file:
      - .env
    networks:
      - proxy
      - default
    labels:
      traefik.frontend.rule: "Host:cloud.${DOMAIN}"
      traefik.port: 80
      traefik.docker.network: proxy
