version: "3"

networks:
  proxy:
    external: true

services:
  smokeping:
    image: linuxserver/smokeping
    networks:
      - proxy
    volumes:
      - "./config:/config:ro" # ro because the image tries to write there and "fix" permissions and other sadness
    env_file:
      - .env
    labels:
      traefik.backend: "smokeping"
      traefik.port: 80
      traefik.frontend.rule: "Host:smokeping.vsecko.doma"
      traefik.docker.network: proxy
